"""
Modo automático: el servidor encadena las cinco etapas (ontología → grafo →
preparación → simulación → informe) aunque el usuario cierre la pestaña.

Hace la misma secuencia y con los mismos parámetros que la pantalla, llamando
a las mismas rutas con `app.test_client()` y el secreto interno del proceso
(sin token de usuario y sin contar para el rate limit). La única etapa que no
pasa por una ruta es la ontología: el proyecto se crea en la petición y la
ontología se genera aquí con el mismo helper que usa `ontology/generate`.

Cada etapa comprueba primero si ya está hecha, así que reanudar es volver a
recorrerlas: se saltan las completadas y se reutilizan proyecto, grafo,
simulación e informe.
"""

import threading
import time
import traceback
import uuid
from typing import Any, Callable, Dict, Optional, Tuple

from ..models.project import ProjectManager, ProjectStatus
from ..utils.locale import set_locale
from ..utils.logger import get_logger
from ..utils.security import internal_request_headers
from .pipeline_state import (
    now_iso,
    pipeline_lock,
    public_view,
    read_pipeline,
    update_pipeline,
    write_pipeline,
)
from .report_agent import ReportManager
from .simulation_manager import SimulationManager
from .simulation_runner import SimulationRunner

logger = get_logger('mirofish.pipeline')

# ============== Tiempos ==============

GRAPH_TIMEOUT_SECONDS = 30 * 60
PREPARE_TIMEOUT_SECONDS = 30 * 60
SIMULATION_TIMEOUT_SECONDS = 6 * 60 * 60
REPORT_TIMEOUT_SECONDS = 45 * 60
POLL_SECONDS = 5
# Margen para una simulación que otro (la pantalla) está arrancando justo ahora
STARTING_GRACE_SECONDS = 60

# ============== Parámetros: los mismos que manda la pantalla ==============

# Step2EnvSetup.vue: useCustomRounds = true y customMaxRounds = 40 por defecto
# (el tope autoGeneratedRounds nunca baja de 40). Sin él la configuración
# automática puede dar 72–168 rondas y tardar horas.
AUTO_MAX_ROUNDS = 40
# Step1GraphBuild.vue → POST /api/simulation/create
ENABLE_TWITTER = True
ENABLE_REDDIT = True
# Step2EnvSetup.vue → POST /api/simulation/prepare
USE_LLM_FOR_PROFILES = True
PARALLEL_PROFILE_COUNT = 5


class PipelineConflict(Exception):
    """Ya hay un modo automático en marcha para el proyecto (409)."""


class StageFailed(Exception):
    """Una etapa ha fallado; el mensaje va al campo `error` del estado."""


class _StageTimeout(StageFailed):
    """Una etapa superó su tiempo máximo."""


class _RunStopped(Exception):
    """La ejecución dejó de ser la vigente (cancelada, relevada o proyecto borrado)."""


# ============== Cliente interno ==============

class InternalApiClient:
    """Llama a las rutas de la propia app como lo haría la pantalla."""

    def __init__(self, app, locale: str):
        self._client = app.test_client()
        self._headers = {**internal_request_headers(), "Accept-Language": locale or "es"}

    def get(self, path: str) -> Tuple[int, Dict[str, Any]]:
        return self._request("GET", path)

    def post(self, path: str, payload: Dict[str, Any]) -> Tuple[int, Dict[str, Any]]:
        return self._request("POST", path, payload)

    def _request(self, method: str, path: str, payload=None) -> Tuple[int, Dict[str, Any]]:
        response = self._client.open(path, method=method, json=payload, headers=self._headers)
        body = response.get_json(silent=True)
        return response.status_code, body if isinstance(body, dict) else {}


def _ok(status: int, body: Dict[str, Any]) -> bool:
    return 200 <= status < 300 and body.get("success") is True


def _api_error(status: int, body: Dict[str, Any], fallback: str) -> str:
    message = body.get("error") if isinstance(body, dict) else None
    if not message:
        message = f"{fallback} (HTTP {status})"
    data = body.get("data") if isinstance(body, dict) else None
    hint = data.get("hint") if isinstance(data, dict) else None
    return f"{message} {hint}" if hint else str(message)


# ============== Reglas de fin de simulación (las de Step3Simulation.vue) ==============

def platforms_completed(data: Dict[str, Any]) -> bool:
    """Misma regla que checkPlatformsCompleted: todas las plataformas activas terminaron."""
    if not data:
        return False
    twitter_done = data.get("twitter_completed") is True
    reddit_done = data.get("reddit_completed") is True
    twitter_enabled = (data.get("twitter_actions_count") or 0) > 0 or bool(data.get("twitter_running")) or twitter_done
    reddit_enabled = (data.get("reddit_actions_count") or 0) > 0 or bool(data.get("reddit_running")) or reddit_done
    if not twitter_enabled and not reddit_enabled:
        return False
    if twitter_enabled and not twitter_done:
        return False
    if reddit_enabled and not reddit_done:
        return False
    return True


def run_failed(data: Dict[str, Any]) -> bool:
    return data.get("runner_status") == "failed" or data.get("status") == "failed"


def run_finished(data: Dict[str, Any], stopped_counts: bool = True) -> bool:
    status = data.get("runner_status")
    if status == "completed" or platforms_completed(data):
        return True
    return stopped_counts and status == "stopped"


def run_running(data: Dict[str, Any]) -> bool:
    return (
        data.get("runner_status") in ("running", "starting")
        or bool(data.get("twitter_running"))
        or bool(data.get("reddit_running"))
    )


def _needs_simulation(data: Dict[str, Any], previous_stage: Optional[str]) -> bool:
    """
    ¿Hay que lanzar (o esperar) la simulación? Solo se salta si la ejecución
    anterior terminó. Un `failed` nunca cuenta como terminada. Si el pipeline
    anterior se cortó en esta misma etapa, un `stopped` es suyo (cancelación o
    reinicio del servidor): tampoco terminó. Fuera de eso, `stopped` cuenta como
    terminada, igual que en la pantalla (el usuario la paró a mano).
    """
    if run_failed(data):
        return True
    return not run_finished(data, stopped_counts=(previous_stage != "simulate"))


# ============== Comprobaciones de lo que ya está hecho (solo lectura) ==============

def _ontology_done(project) -> bool:
    return bool(project.ontology)


def _graph_done(project) -> bool:
    return project.status == ProjectStatus.GRAPH_COMPLETED and bool(project.graph_id)


def _latest_simulation_id(project_id: str, preferred: Optional[str] = None) -> Optional[str]:
    """La simulación del pipeline si sigue existiendo; si no, la más reciente del proyecto."""
    manager = SimulationManager()
    if preferred:
        try:
            state = manager.get_simulation(preferred)
        except ValueError:
            state = None
        if state and state.project_id == project_id:
            return preferred
    simulations = manager.list_simulations(project_id=project_id)
    if not simulations:
        return None
    simulations.sort(key=lambda s: s.created_at or "", reverse=True)
    return simulations[0].simulation_id


def _is_prepared(simulation_id: str) -> bool:
    # Import diferido: api.simulation importa este módulo (historial)
    from ..api.simulation import _check_simulation_prepared
    prepared, _info = _check_simulation_prepared(simulation_id)
    return prepared


def _run_state_dict(simulation_id: str) -> Dict[str, Any]:
    run_state = SimulationRunner.get_run_state(simulation_id)
    return run_state.to_dict() if run_state else {"runner_status": "idle"}


def _latest_completed_report_id(simulation_id: str) -> Optional[str]:
    reports = ReportManager.list_reports(simulation_id=simulation_id, limit=1)
    if not reports:
        return None
    status = getattr(reports[0].status, "value", reports[0].status)
    return reports[0].report_id if status == "completed" else None


def _is_alive(simulation_id: str) -> bool:
    return simulation_id in SimulationRunner.get_running_simulations()


def _estimate_stage(project, previous_stage: Optional[str]) -> Tuple[str, Optional[str]]:
    """Primera etapa sin completar (para que la respuesta de resume ya diga adónde ir)."""
    if not _ontology_done(project):
        return "ontology", None
    if not _graph_done(project):
        return "graph", None
    simulation_id = _latest_simulation_id(project.project_id)
    if not simulation_id or not _is_prepared(simulation_id):
        return "prepare", simulation_id
    if _needs_simulation(_run_state_dict(simulation_id), previous_stage):
        return "simulate", simulation_id
    return "report", simulation_id


# ============== Registro de ejecuciones vivas (un solo proceso) ==============

_ACTIVE_RUNS: Dict[str, "AutoPipelineRunner"] = {}
_ACTIVE_LOCK = threading.Lock()


def _register(runner: "AutoPipelineRunner") -> None:
    with _ACTIVE_LOCK:
        _ACTIVE_RUNS[runner.project_id] = runner


def _unregister(runner: "AutoPipelineRunner") -> None:
    with _ACTIVE_LOCK:
        if _ACTIVE_RUNS.get(runner.project_id) is runner:
            _ACTIVE_RUNS.pop(runner.project_id, None)


def _is_run_alive(project_id: str, run_id: Optional[str]) -> bool:
    with _ACTIVE_LOCK:
        runner = _ACTIVE_RUNS.get(project_id)
        return bool(runner and run_id and runner.run_id == run_id)


def active_runner(project_id: str) -> Optional["AutoPipelineRunner"]:
    with _ACTIVE_LOCK:
        return _ACTIVE_RUNS.get(project_id)


def stop_simulation_if_running(api: InternalApiClient, simulation_id: Optional[str]) -> bool:
    """Detiene la simulación (POST /api/simulation/stop → SimulationRunner.stop_simulation) si corre."""
    if not simulation_id:
        return False
    try:
        status, body = api.get(f"/api/simulation/{simulation_id}/run-status")
        data = body.get("data") or {}
        if not _ok(status, body) or data.get("runner_status") not in ("running", "paused", "starting"):
            return False
        status, body = api.post("/api/simulation/stop", {"simulation_id": simulation_id})
        if _ok(status, body):
            logger.info(f"[pipeline] Simulación {simulation_id} detenida")
            return True
        logger.warning(f"[pipeline] No se pudo detener la simulación {simulation_id}: {body.get('error')}")
    except Exception as exc:  # noqa: BLE001 — detener es best-effort
        logger.warning(f"[pipeline] Error al detener la simulación {simulation_id}: {exc}")
    return False


# ============== El hilo ==============

class AutoPipelineRunner:
    def __init__(
        self,
        app,
        project_id: str,
        run_id: str,
        locale: str,
        previous_stage: Optional[str] = None,
        document_texts=None,
        additional_context: Optional[str] = None,
    ):
        self.project_id = project_id
        self.run_id = run_id
        self.locale = locale
        self.previous_stage = previous_stage
        self.document_texts = document_texts
        self.additional_context = additional_context
        self.api = InternalApiClient(app, locale)
        self.cancel_event = threading.Event()
        self.thread = threading.Thread(target=self.run, name=f"pipeline-{project_id}", daemon=True)
        self._simulation_id: Optional[str] = None
        # Si esta ejecución lanzó o esperó la simulación, un informe anterior ya no vale
        self._simulation_ran = False

    @property
    def _tag(self) -> str:
        return f"[pipeline {self.project_id}]"

    def run(self):
        set_locale(self.locale)
        logger.info(f"{self._tag} Arranca el modo automático (ejecución {self.run_id[:8]})")
        try:
            self._stage_ontology()
            graph_id = self._stage_graph()
            simulation_id = self._stage_prepare(graph_id)
            self._stage_simulate(simulation_id)
            self._stage_report(simulation_id)
            self._finish("completed", stage="done")
            logger.info(f"{self._tag} Modo automático completado")
        except _RunStopped:
            self._after_stop()
        except StageFailed as exc:
            logger.warning(f"{self._tag} Etapa fallida: {exc}")
            self._finish("failed", error=str(exc))
        except Exception as exc:  # noqa: BLE001 — el hilo no puede morir sin dejar el estado en failed
            logger.error(f"{self._tag} Error inesperado: {exc}")
            logger.debug(traceback.format_exc())
            self._finish("failed", error=f"Error interno del modo automático: {exc}")
        finally:
            _unregister(self)

    # ---------- estado ----------

    def _finish(self, status: str, stage: Optional[str] = None, error: Optional[str] = None):
        fields = {"status": status, "finished_at": now_iso(), "error": error}
        if stage:
            fields["stage"] = stage
        try:
            update_pipeline(self.project_id, self.run_id, **fields)
        except Exception as exc:  # noqa: BLE001
            logger.error(f"{self._tag} No se pudo guardar el estado final ({status}): {exc}")

    def _update(self, **fields):
        if update_pipeline(self.project_id, self.run_id, **fields) is None:
            raise _RunStopped()

    def _enter_stage(self, stage: str, **fields):
        # Se escribe ANTES de lanzar la etapa: la pantalla sabe adónde ir
        logger.info(f"{self._tag} Etapa «{stage}»")
        self._update(stage=stage, **fields)

    def _checkpoint(self):
        if self.cancel_event.is_set():
            raise _RunStopped()
        state = read_pipeline(self.project_id)
        if not state or state.get("run_id") != self.run_id or state.get("status") != "running":
            raise _RunStopped()

    def _sleep(self):
        if self.cancel_event.wait(POLL_SECONDS):
            raise _RunStopped()

    def _poll(self, check: Callable[[], bool], timeout_seconds: float, label: str):
        """Sondea `check` cada POLL_SECONDS hasta que devuelva True (o lance StageFailed)."""
        deadline = time.monotonic() + timeout_seconds
        while True:
            self._checkpoint()
            if check():
                return
            if time.monotonic() >= deadline:
                minutes = max(1, round(timeout_seconds / 60))
                raise _StageTimeout(f"Tiempo de espera agotado en {label} ({minutes} min)")
            self._sleep()

    def _after_stop(self):
        try:
            state = read_pipeline(self.project_id)
            if state and state.get("run_id") == self.run_id and state.get("status") == "cancelled":
                # Pudo lanzar la simulación justo después de la cancelación
                stop_simulation_if_running(self.api, self._simulation_id or state.get("simulation_id"))
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"{self._tag} Error al cerrar una ejecución detenida: {exc}")
        logger.info(f"{self._tag} Ejecución detenida (cancelada o relevada)")

    def _project(self):
        project = ProjectManager.get_project(self.project_id)
        if project is None:
            logger.warning(f"{self._tag} El proyecto ya no existe: se detiene el modo automático")
            raise _RunStopped()
        return project

    # ---------- etapa 1a: ontología ----------

    def _stage_ontology(self):
        project = self._project()
        if _ontology_done(project):
            return
        self._enter_stage("ontology")

        texts = self.document_texts
        if not texts:
            # Reanudación: el texto de todos los documentos ya está extraído en disco
            extracted = ProjectManager.get_extracted_text(self.project_id)
            if not extracted:
                raise StageFailed("No hay texto extraído de los documentos del proyecto: vuelve a subir el brief")
            texts = [extracted]

        from ..api.graph import generate_project_ontology  # import diferido: evita el ciclo services ↔ api
        project.error = None
        try:
            generate_project_ontology(project, texts, self.additional_context)
        except Exception as exc:  # noqa: BLE001 — cualquier fallo del LLM acaba la etapa
            # A diferencia de la ruta manual, el proyecto no se borra: queda con
            # su error y el usuario puede reanudar.
            try:
                failed = ProjectManager.get_project(self.project_id)
                if failed:
                    failed.error = str(exc)
                    ProjectManager.save_project(failed)
            except Exception as save_exc:  # noqa: BLE001
                logger.warning(f"{self._tag} No se pudo guardar el error en el proyecto: {save_exc}")
            raise StageFailed(f"Fallo al generar la ontología: {exc}")
        self.document_texts = None
        self._checkpoint()

    # ---------- etapa 1b: grafo ----------

    def _stage_graph(self) -> str:
        project = self._project()
        if _graph_done(project):
            return project.graph_id
        self._enter_stage("graph")

        task_id = None
        if project.status == ProjectStatus.GRAPH_BUILDING:
            # Construcción en curso (la pantalla o una ejecución anterior):
            # GET /project se autorrepara si la tarea murió; si sigue viva, se espera.
            self.api.get(f"/api/graph/project/{self.project_id}")
            project = self._project()
            if _graph_done(project):
                return project.graph_id
            if project.status == ProjectStatus.GRAPH_BUILDING:
                task_id = project.graph_build_task_id

        if not task_id:
            status, body = self.api.post("/api/graph/build", {"project_id": self.project_id})
            if _ok(status, body):
                task_id = (body.get("data") or {}).get("task_id")
            elif status == 409:
                task_id = body.get("task_id") or self._project().graph_build_task_id
                if not task_id:
                    raise StageFailed(_api_error(status, body, "El grafo ya se está construyendo"))
            else:
                raise StageFailed(_api_error(status, body, "No se pudo lanzar la construcción del grafo"))

        def check() -> bool:
            status, body = self.api.get(f"/api/graph/task/{task_id}")
            if status == 404:
                if _graph_done(self._project()):
                    return True
                raise StageFailed("La tarea de construcción del grafo ya no existe")
            if not _ok(status, body):
                raise StageFailed(_api_error(status, body, "No se pudo consultar la construcción del grafo"))
            task = body.get("data") or {}
            if task.get("status") == "completed":
                return True
            if task.get("status") == "failed":
                # project.error es el motivo limpio; task.error lleva el traceback
                failed = ProjectManager.get_project(self.project_id)
                raise StageFailed(
                    (failed.error if failed else None) or task.get("message") or "Falló la construcción del grafo"
                )
            return False

        self._poll(check, GRAPH_TIMEOUT_SECONDS, "la construcción del grafo")

        status, body = self.api.get(f"/api/graph/project/{self.project_id}")
        data = body.get("data") or {}
        if not _ok(status, body) or data.get("status") != "graph_completed" or not data.get("graph_id"):
            raise StageFailed(
                body.get("error") or data.get("error")
                or "La construcción del grafo terminó pero el proyecto no quedó en graph_completed"
            )
        return data["graph_id"]

    # ---------- etapa 2: preparación ----------

    def _stage_prepare(self, graph_id: str) -> str:
        state = read_pipeline(self.project_id) or {}
        # Nunca una segunda simulación: se reutiliza la del pipeline o la más reciente del proyecto
        simulation_id = _latest_simulation_id(self.project_id, preferred=state.get("simulation_id"))
        if simulation_id and _is_prepared(simulation_id):
            self._simulation_id = simulation_id
            self._update(simulation_id=simulation_id)
            return simulation_id

        self._enter_stage("prepare")
        if not simulation_id:
            status, body = self.api.post("/api/simulation/create", {
                "project_id": self.project_id,
                "graph_id": graph_id,
                "enable_twitter": ENABLE_TWITTER,
                "enable_reddit": ENABLE_REDDIT,
            })
            if not _ok(status, body):
                raise StageFailed(_api_error(status, body, "No se pudo crear la simulación"))
            simulation_id = (body.get("data") or {}).get("simulation_id")
            if not simulation_id:
                raise StageFailed("La creación de la simulación no devolvió simulation_id")
        else:
            logger.info(f"{self._tag} Se reutiliza la simulación {simulation_id}")
        self._simulation_id = simulation_id
        self._update(simulation_id=simulation_id)

        status, body = self.api.post("/api/simulation/prepare", {
            "simulation_id": simulation_id,
            "use_llm_for_profiles": USE_LLM_FOR_PROFILES,
            "parallel_profile_count": PARALLEL_PROFILE_COUNT,
        })
        if not _ok(status, body):
            raise StageFailed(_api_error(status, body, "No se pudo lanzar la preparación de la simulación"))
        data = body.get("data") or {}
        if data.get("already_prepared"):
            return simulation_id
        task_id = data.get("task_id")

        def check() -> bool:
            status, body = self.api.post("/api/simulation/prepare/status", {
                "task_id": task_id,
                "simulation_id": simulation_id,
            })
            if not _ok(status, body):
                # Red de seguridad de la pantalla: la simulación pudo fallar sin tarea
                _sim_status, sim_body = self.api.get(f"/api/simulation/{simulation_id}")
                sim = sim_body.get("data") or {}
                if sim.get("status") == "failed":
                    raise StageFailed(sim.get("error") or "Falló la preparación de la simulación")
                raise StageFailed(_api_error(status, body, "No se pudo consultar la preparación"))
            progress = body.get("data") or {}
            if progress.get("status") in ("completed", "ready") or progress.get("already_prepared"):
                return True
            if progress.get("status") == "failed":
                raise StageFailed(progress.get("error") or "Falló la preparación de la simulación")
            return False

        self._poll(check, PREPARE_TIMEOUT_SECONDS, "la preparación de la simulación")
        return simulation_id

    # ---------- etapa 3: simulación ----------

    def _run_status(self, simulation_id: str) -> Dict[str, Any]:
        status, body = self.api.get(f"/api/simulation/{simulation_id}/run-status")
        if not _ok(status, body):
            raise StageFailed(_api_error(status, body, "No se pudo consultar el estado de la simulación"))
        return body.get("data") or {}

    def _stage_simulate(self, simulation_id: str):
        self._simulation_id = simulation_id
        data = self._run_status(simulation_id)
        if not _needs_simulation(data, self.previous_stage):
            logger.info(f"{self._tag} La simulación {simulation_id} ya terminó: no se relanza")
            return

        self._enter_stage("simulate", simulation_id=simulation_id)
        self._simulation_ran = True

        # Si alguien (la pantalla) la está arrancando justo ahora, darle unos segundos
        deadline = time.monotonic() + STARTING_GRACE_SECONDS
        while data.get("runner_status") == "starting" and not _is_alive(simulation_id) \
                and time.monotonic() < deadline:
            self._sleep()
            self._checkpoint()
            data = self._run_status(simulation_id)

        if _is_alive(simulation_id) and run_running(data) and not run_failed(data):
            logger.info(f"{self._tag} La simulación {simulation_id} ya está en marcha: se espera")
        else:
            # Relanzar (force) solo si hubo una ejecución anterior que no terminó
            relaunch = data.get("runner_status") not in (None, "idle")
            self._start_simulation(simulation_id, force=relaunch)

        def check() -> bool:
            data = self._run_status(simulation_id)
            if run_failed(data):
                raise StageFailed(data.get("error") or "La simulación falló")
            return run_finished(data, stopped_counts=True)

        try:
            self._poll(check, SIMULATION_TIMEOUT_SECONDS, "la simulación")
        except _StageTimeout:
            # Una simulación colgada sigue gastando LLM: se para antes de fallar
            stop_simulation_if_running(self.api, simulation_id)
            raise

    def _start_simulation(self, simulation_id: str, force: bool):
        # Sin max_rounds la configuración automática puede dar 72–168 rondas
        status, body = self.api.post("/api/simulation/start", {
            "simulation_id": simulation_id,
            "platform": "parallel",
            "force": force,
            "enable_graph_memory_update": True,
            "max_rounds": AUTO_MAX_ROUNDS,
        })
        if _ok(status, body):
            return
        # Carrera con la pantalla: si ya está en marcha, cuenta como arrancada y
        # se espera con run-status (sin marcar fallo ni relanzar con force).
        data = self._run_status(simulation_id)
        if _is_alive(simulation_id) or (run_running(data) and not run_failed(data)):
            logger.info(f"{self._tag} /start respondió {status} pero la simulación ya está en marcha: se espera")
            return
        raise StageFailed(_api_error(status, body, "No se pudo iniciar la simulación"))

    # ---------- etapa 4: informe ----------

    def _stage_report(self, simulation_id: str):
        if not self._simulation_ran:
            existing = _latest_completed_report_id(simulation_id)
            if existing:
                logger.info(f"{self._tag} Se reutiliza el informe {existing}")
                self._update(report_id=existing)
                return

        self._enter_stage("report", report_id=None)
        status, body = self.api.post("/api/report/generate", {
            "simulation_id": simulation_id,
            "force_regenerate": True,
        })
        if status == 409:
            # Incluye el 409 «recoverable» (simulación fallida con datos parciales): no se fuerza
            raise StageFailed(_api_error(status, body, "El informe necesita una simulación completada"))
        if not _ok(status, body):
            raise StageFailed(_api_error(status, body, "No se pudo lanzar la generación del informe"))

        data = body.get("data") or {}
        self._update(report_id=data.get("report_id"))
        if data.get("already_generated") or data.get("status") == "completed":
            return
        task_id = data.get("task_id")

        def check() -> bool:
            # Solo task_id: con simulation_id la ruta devuelve el informe
            # completado anterior aunque se esté regenerando
            status, body = self.api.post("/api/report/generate/status", {"task_id": task_id})
            if not _ok(status, body):
                raise StageFailed(_api_error(status, body, "No se pudo consultar la generación del informe"))
            progress = body.get("data") or {}
            if progress.get("status") == "completed":
                return True
            if progress.get("status") == "failed":
                raise StageFailed(progress.get("error") or "Falló la generación del informe")
            return False

        self._poll(check, REPORT_TIMEOUT_SECONDS, "la generación del informe")


# ============== API del módulo (la usan las rutas) ==============

def start_pipeline(
    app,
    project_id: str,
    *,
    locale: str,
    document_texts=None,
    additional_context: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Arranca el modo automático (proyecto recién creado, con `document_texts`)
    o lo reanuda desde la primera etapa sin completar. PipelineConflict si ya
    hay una ejecución viva para el proyecto.
    """
    with pipeline_lock(project_id):
        current = read_pipeline(project_id)
        if current and current.get("status") == "running":
            if _is_run_alive(project_id, current.get("run_id")):
                raise PipelineConflict("Ya hay un modo automático en marcha para este proyecto")
            logger.warning(f"[pipeline {project_id}] Estado running sin hilo vivo: se releva")

        project = ProjectManager.get_project(project_id)
        if project is None:
            raise LookupError(project_id)

        previous_stage = current.get("stage") if current else None
        if additional_context is None and current:
            additional_context = current.get("additional_context") or None

        if document_texts is not None:
            stage, simulation_id = "ontology", None
        else:
            stage, simulation_id = _estimate_stage(project, previous_stage)

        run_id = uuid.uuid4().hex
        state = {
            "mode": "auto",
            "status": "running",
            "stage": stage,
            "project_id": project_id,
            "simulation_id": simulation_id,
            "report_id": None,
            "error": None,
            "started_at": now_iso(),
            "finished_at": None,
            # Internos (no salen al cliente)
            "run_id": run_id,
            "additional_context": additional_context or "",
        }
        write_pipeline(project_id, state)

        runner = AutoPipelineRunner(
            app,
            project_id,
            run_id,
            locale,
            previous_stage=previous_stage,
            document_texts=document_texts,
            additional_context=additional_context,
        )
        _register(runner)
        runner.thread.start()

    logger.info(f"[pipeline {project_id}] Modo automático lanzado desde la etapa «{stage}»")
    return public_view(state)


def cancel_pipeline(app, project_id: str, *, locale: str) -> Dict[str, Any]:
    """Para el bucle y detiene la simulación si corre. Idempotente."""
    simulation_to_stop = None
    with pipeline_lock(project_id):
        state = read_pipeline(project_id)
        if not state:
            return public_view(None)
        if state.get("status") == "running":
            state.update(status="cancelled", finished_at=now_iso(), error=None)
            write_pipeline(project_id, state)
            runner = active_runner(project_id)
            if runner and runner.run_id == state.get("run_id"):
                runner.cancel_event.set()
            simulation_to_stop = state.get("simulation_id")
            logger.info(f"[pipeline {project_id}] Modo automático cancelado en la etapa «{state.get('stage')}»")

    if simulation_to_stop:
        stop_simulation_if_running(InternalApiClient(app, locale), simulation_to_stop)
    return public_view(state)


def get_pipeline_state(project_id: str) -> Dict[str, Any]:
    with pipeline_lock(project_id):
        state = read_pipeline(project_id)
        if state and state.get("status") == "running" and not _is_run_alive(project_id, state.get("run_id")):
            # Ningún hilo de este proceso la lleva (no debería pasar sin reinicio)
            state.update(
                status="interrupted",
                finished_at=now_iso(),
                error="El modo automático se detuvo sin terminar. Puedes reanudarlo.",
            )
            write_pipeline(project_id, state)
    return public_view(state)


def get_pipeline_summary(project_id: str) -> Dict[str, Any]:
    """Para el historial: modo y estado, sin escribir nada."""
    state = read_pipeline(project_id)
    if not state or state.get("mode") != "auto":
        return {"pipeline_mode": "manual", "pipeline_status": None}
    status = state.get("status")
    if status == "running" and not _is_run_alive(project_id, state.get("run_id")):
        status = "interrupted"
    return {"pipeline_mode": "auto", "pipeline_status": status}
